server:
  port: 8081
spring:
  application:
    name: shop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shopApp
    username: root
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  flyway:
    user: root
    password: 123
    url: jdbc:postgresql://localhost:5432/shopApp